name: Rotation Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install packages
        run: pip install numpy pandas yfinance scikit-learn requests

      - name: Run model
        run: python model_c_plus_usd_hyg_short_conviction.py
